//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock_Paper_Scissors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int idPlayer { get; set; }
        public string Name { get; set; }
        public int Points { get; set; }
    }
}
